when@dev:
    monolog:
        handlers:
            file:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            file:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
            console:
                type: console
                process_psr_3_messages: false
                channels: [ "!event", "!doctrine", "!console" ]

when@prod:
    monolog:
        handlers:
            file:
                type: rotating_file
                path: "%kernel.logs_dir%/prod/%kernel.environment%.log"
                level: error
                max_files: 10
